---
kind: pipeline
name: linux
type: docker

platform:
  os: linux
  arch: amd64

environment:
  DEBIAN_FRONTEND: "noninteractive"
  SDK_TEST_BASE_URL: "https://artifactory.mersive.xyz/artifactory/android/"

steps:
  - name: gstreamer build
    image: artifactory.mersive.xyz/docker-public/gstreamer-android-builder
    commands:
      - printenv
      # the localconf is important because it lets use prefetched plugin source and NDK toolchains from the container build
      # this helps to substantially speed up the build by avoiding a bunch of downloads
      - ./cerbero-uninstalled -c /cerbero/localconf.cbc -c config/cross-android-universal.cbc package gstreamer-1.0
  - name: Deploy Artifacts
    image: artifactory.mersive.xyz/docker-public/gstreamer-android-builder
    commands:
      - bash deploy.sh
    environment:
      ARTIFACTORY_PASSWORD:
        from_secret: artifactory-password
trigger:
  ref:
    - refs/heads/mersive_build
    - refs/tags/*
    - refs/pull/*/head
---
kind: secret
name: artifactory-password
get:
  path: drone/data/cerbero/artifactory-password
  name: password
